---
title: "Practical One"
format: html
---

## Question 1:
Finding all the rows with missing values from the "airquality" dataset

```{r}
class(airquality)

airquality_with_missingvalues <<- airquality[
  is.na(airquality$Ozone) | is.na(airquality$Solar.R) | 
    is.na(airquality$Wind) | is.na(airquality$Temp) | 
    is.na(airquality$Month) | is.na(airquality$Day),]

print(airquality_with_missingvalues)

write.csv(airquality_with_missingvalues, file = "_raw_data/dataset.csv") #saving our manipulated data 
```

## Question 2:
Finding mean, sd, min, max for each of temperature and ozone level

```{r}
airquality_with_missingvalues <- read.csv("_raw_data/dataset.csv")
  
ozone_mean <- mean(airquality_with_missingvalues$Ozone, na.rm = TRUE)
ozone_mean
ozone_sd <- sd(airquality_with_missingvalues$Ozone, na.rm = TRUE)
ozone_sd
ozone_min <- min(airquality_with_missingvalues$Ozone, na.rm = TRUE)
ozone_min
ozone_max <- max (airquality_with_missingvalues$Ozone, na.rm = TRUE)
ozone_max
  
temp_mean <- mean(airquality_with_missingvalues$Temp)
temp_mean
temp_sd <- sd(airquality_with_missingvalues$Temp)
temp_sd
temp_min <- min(airquality_with_missingvalues$Temp)
temp_min
temp_max <- max(airquality_with_missingvalues$Temp)
temp_max
```

## Question 3:
Estimating the parameters for linear regression model (distance\~speed) from the cars data set

```{r}
y_matrix <- cars$dist
x_matrix <- cbind(1, cars$speed)

linear_reg <- function(x, y) {
  num_observations <- nrow(x)
  num_variables <- ncol(x)

  beta_hat <- solve(t(x) %*% x) %*% t(x) %*% y  # beta estimate 

  regression_residuals <- y - x %*% beta_hat

  rss <- t(regression_residuals) %*% regression_residuals  # residual sum of squares

  regression_variance <- as.numeric(rss) / (num_observations - num_variables)  

  standard_errors <- sqrt(diag(regression_variance * solve(t(x) %*% x)))  

  t_stats <- beta_hat / standard_errors  

  p_vals <- 2 * (1 - pt(abs(t_stats), num_observations - num_variables))

  return(list(
    "beta estimates:" = beta_hat, 
    "estimate standard errors:" = standard_errors, 
    "t statistics:" = t_stats, 
    "P-values:" = p_vals
  ))
}

linear_reg(x_matrix, y_matrix)
```


